### ISSUE TITLE
Issues in MetaWorks 1.10.0 tutorial

### ISSUE THREAD

**Issue by MunozAdalia** [terrimporter/MetaWorks#5]
Dear all,

I am a beginner user of MetaWorks. I was working with tutorial provided in the webpage (https://terrimporter.github.io/MetaWorksSite/tutorial/), nevertheless I found some issues that I could not fix by my own. I hope you could help me.

1. When I write in my Linux console the step:
"t: "/path/to/CO1Classifier/v4/mydata_trained/rRNAClassifier.properties""
I found "t:: order not found". I do not know how to fix this issue (and its source)

2. I tried to run the following step, because I am working with training data and I guess it could work without specifying a special path for the classifier:
"snakemake --jobs 2 --snakefile snakefile --configfile config_testing_COI_data.yaml"
The console said "Error: Snakefile "snakefile" not found". So, the program is not working. Which directory is required to be in for running this command?

3. The path for downloading the most recent version of the program is not working, so I worked with manually downloaded files from: https://github.com/terrimporter/MetaWorks/releases/tag/v1.10.0 (I downloaded "MetaWorks1.10.0.zip" and everything seemed to be working fine. Is it correct?

I hope you could help me to understand the usage of this interesting program.

Regards.

**Comment by terrimporter** [comment]
Have you replaced /path/to/CO1Classifier/v4/mydata_trained/rRNAClassifier.properties with the actual path to this file on your system?

**Comment by terrimporter** [comment]
I've updated the download link, thanks for letting me know!

**Comment by terrimporter** [comment]
I've also updated snakefile to snakefile_ESV in  the tutorial documentation.  Thanks again.  The command for running the test data should be: snakemake --jobs 2 --snakefile snakefile_ESV --configfile config_testing_COI_data.yaml

**Comment by MunozAdalia** [comment]
Thank you so much for your explanation. I tried the original code, nevertheless I will try again with these new instructions and share the results. Regards!

**Comment by MunozAdalia** [comment]
I have tried the new tutorial using MetaWorks1.11.0.

When I tried "conda activate MetaWorks_v1.11.0"
I found this error:
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run
    $ conda init <SHELL_NAME>
How can I fix this issue?
Thanks in advance

**Comment by terrimporter** [comment]
To find out what shell you're using type:
echo $SHELL

Then run conda init (only need to do this the first time you use conda):
conda init bash

Replace 'bash' with whatever shell you're actually running.

Then close and re-start your terminal for the changes to take effect.

I've added these instructions to the tutorial as well.

**Comment by MunozAdalia** [comment]
Thanks again,

A) I do not completely understand how to indicate the path for "rRNAClassifier.properties". I have the default file in the default folder (i.e. ~/MetaWorks1.11.0/mydata_trained$ (*))
t:"/path/to/CO1Classifier/v4/mydata_trained/rRNAClassifier.properties" 

#it does not work in my terminal, probably because the path is not correct, nevertheles if I indicate the (*) path it neither works.

B) I tried to run the conda command,
I executed:
(base) pc@pc-VirtualBox:~/MetaWorks1.11.0$ conda activate MetaWorks_v1.11.0

#it seems to work#
(MetaWorks_v1.11.0) pc@pc-VirtualBox:~/MetaWorks1.11.0$ snakemake --jobs 2 --snakefile snakefile_ESV --configfile config_testing_COI_data.yaml

#it starts to work but I could not find the results... in fact the following error appears:
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /path/to/mydata_trained/rRNAClassifier.properties (the file or directory does not exist)
[...] ... 3 more
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-08-24T182828.406150.snakemake.log

Regards,

**Comment by terrimporter** [comment]
MetaWorks won't run completely because you haven't specified where to find the trained COI classifier.

'Path' indicates where in your filesystem to find the file rRNAClassifier.properties file.

Have you downloaded and unzipped the CO1 Classifier from here? 
https://github.com/terrimporter/CO1Classifier/releases/tag/v4.0.1

Once it's installed, browse to where you see the file rRNAClassifier.properties.

Then do:
pwd

This will give you the 'path' to the file.  Don't forget to add the name of the file itself too when updating the config file.

**Comment by MunozAdalia** [comment]
Thank again for your time and useful advice.

I manually checked where is "rRNAClasiffier.properties" in my computer:
~/MetaWorks1.11.0/mydata_trained
Because, if I used "pwd" it shows "home" as response (that is not true)

Well, after that I tried a huge variety of possibilities for command line "t:"
t:"/home/pc/MetaWorks1.11.0/mydata_trained/rRNAClassifier.properties"
t:"/path/home/pc/MetaWorks1.11.0/mydata_trained/rRNAClassifier.properties"
t:"/path/to/home/pc/MetaWorks1.11.0/mydata_trained/rRNAClassifier.properties"
t:"/path/to/pc/home/MetaWorks1.11.0/mydata_trained/rRNAClassifier.properties"

Any of these lines worked properly... always "the file or directory does not exist"

Consequently, I cannot indicate where the classifier properties are and conda cannot run well.

**Comment by terrimporter** [comment]
I just want to confirm that you're working at the command line and not clicking through windows on your linux x64 system?  If you physically change directories, at the command-line, to where you see the rRNAClassifier.properties file, and do pwd, all it does is show /home?

It looks like you placed the mydata_trained folder into your Metaworks1.11.0 directory?  If that's the case then just do:
t:"mydata_trained/rRNAClassifier.properties"

**Comment by Jess-Schultz** [comment]
Hi there!
I am also experiencing difficulty with the Tutorial.  I am new to coding and MetaWorks.  I have edited the path to the classifier in the config_testing_COI_data.yaml file, but am still getting the following error: 

Error in rule taxonomic_assignment:
    jobid: 0
    input: COI/cat.denoised.nonchimeras
    output: COI/rdp.out.tmp

RuleException:
CalledProcessError in file /home/innovation-admin/MetaWorks1.12.0/snakefile_ESV, line 343:
Command 'set -euo pipefail;  rdp_classifier -Xmx8g classify -t /home/innovation-admin/MetaWorks1.12.0/mydata/rRNAClassifier.properties -o COI/rdp.out.tmp COI/cat.denoised.nonchimeras' returned non-zero exit status 1.
  File "/home/innovation-admin/MetaWorks1.12.0/snakefile_ESV", line 343, in __rule_taxonomic_assignment
  File "/home/innovation-admin/miniconda3/envs/MetaWorks_v1.12.0/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job taxonomic_assignment since they might be corrupted:
COI/rdp.out.tmp

Any suggestions on what might be going wrong?
Thank you for your help.

**Comment by terrimporter** [comment]
This is a separate issue from the thread above.  I looks like the classifier is not finishing and I suspect there were other error messages before this one such as one that refers to 'java heap space'?  Try increasing the memory allocated to the rdp classifier from -Xmx8g to maybe -Xmx16g in the config file.

**Comment by pedroaslongo** [comment]
Hi there! 

I am am also having trouble with the Tutorial, apperently some classifier-related issue. I have edited the path to the classifier in the config_testing_COI_data.yaml file, I also tried to increase the memory allocated to the rdp classifier in the config file, but it is still not working.  I am getting the following messages:

/home/labecmar/miniconda3/envs/MetaWorks_v1.12.0/bin/rdp_classifier: line 57:  8489 Killed                  /home/labecmar/miniconda3/envs/MetaWorks_v1.12.0/bin/java -Xmx8g -jar /home/labecmar/miniconda3/envs/MetaWorks_v1.12.0/share/rdp_classifier-2.13-1/classifier.jar classify -t mydata/rRNAClassifier.properties -o COI/rdp.out.tmp COI/cat.denoised.nonchimeras

[Thu Aug 17 12:03:34 2023]
Error in rule taxonomic_assignment:
    jobid: 0
    input: COI/cat.denoised.nonchimeras
    output: COI/rdp.out.tmp

RuleException:
CalledProcessError in file /home/labecmar/MetaWorks1.12.0/snakefile_ESV, line 343:
Command 'set -euo pipefail;  rdp_classifier -Xmx8g classify -t mydata/rRNAClassifier.properties -o COI/rdp.out.tmp COI/cat.denoised.nonchimeras' returned non-zero exit status 137.
  File "/home/labecmar/MetaWorks1.12.0/snakefile_ESV", line 343, in __rule_taxonomic_assignment
  File "/home/labecmar/miniconda3/envs/MetaWorks_v1.12.0/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job taxonomic_assignment since they might be corrupted:
COI/rdp.out.tmp
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-17T120233.625360.snakemake.log


Could you please help me solve this issue?
Thank you very much!
